name: astro-i18next-publish

on:
  push:
    branches: [develop, main, alpha, beta]
  pull_request:
    branches: "*"

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Setup node âš™ï¸
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm ğŸ“¦
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Quality check ğŸ‘Œ
        run: |
          pnpm install
          pnpm run typecheck
          pnpm run lint
          pnpm run prettier
          pnpm test

  bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Setup node âš™ï¸
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm ğŸ“¦
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Bundle ğŸ“¦
        run: |
          pnpm install
          pnpm run build

      - name: Upload bundle as artifact ğŸ“¤
        uses: actions/upload-artifact@v3
        with:
          name: bundle
          path: dist/
          retention-days: 1
          if-no-files-found: error

  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/alpha' || github.ref == 'refs/heads/beta'
    needs: [quality, bundle]
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN_SEMANTIC_RELEASE }}

      - name: Setup node âš™ï¸
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm ğŸ“¦
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Download bundle artifact ğŸ“¥
        uses: actions/download-artifact@v3
        with:
          name: bundle
          path: dist

      - name: Release & Publish to NPM ğŸš€
        run: |
          pnpm install
          pnpm run semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
